version: '3'

services:
  adminer:
    image: adminer
    restart: always
    networks:
      - zentao
    ports:
      - 8080:8080
  db:
    build:
      context: .
      dockerfile: Dockerfile_db
    restart: always
    networks:
      - zentao
    environment:
       MYSQL_ROOT_PASSWORD: mypassword
       MYSQL_USER: zentao
       MYSQL_PASSWORD: zentao123
       MYSQL_DATABASE: zentao
    volumes:
      - mariadb_data:/var/lib/mysql
  zendao:
    build: .
    networks:
      - zentao
    restart: always
    ports:
      - 2048:80
    volumes:
      - backup:/var/www/zentaopms/tmp/backup
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 30s
    depends_on:
      - db
  
volumes:
  mariadb_data:
  backup:

networks:
  zentao:
    driver: bridge